apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-1
spec:
  limits:
    - default:
        memory: 0.5Gi
        cpu: 0.5
      defaultRequest:
        memory: 0.5Gi
        cpu: 0.5
      type: Container
      max:
        memory: 1Gi
        cpu: 1
