apiVersion: v1
kind: Secret
metadata:
  name: granulate-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJ1c2VybmFtZSI6ICJncmFudWxhdGV0ZXN0IiwgInBhc3N3b3JkIjogImVlY2QwYjYzLWRhZWYtNDgzYS1hYmM4LWExNmFkYWU5ZWI2MiIsICJhdXRoIjogIlozSmhiblZzWVhSbGRHVnpkRHBsWldOa01HSTJNeTFrWVdWbUxUUTRNMkV0WVdKak9DMWhNVFpoWkdGbE9XVmlOakk9In19fQ==
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: granulate-cluster-role
rules:
- apiGroups:
  - ''
  - apps
  - extensions
  resources:
  - nodes
  - pods
  - services
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ''
  - apps
  - extensions
  - policy
  resources:
  - endpoints
  - namespaces
  - limitranges
  - resourcequotas
  - persistentvolumes
  - persistentvolumeclaims
  - poddisruptionbudget
  - pods/log
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes/spec
  - nodes/stats
  - nodes/proxy
  - nodes/metrics
  verbs:
  - get
- apiGroups:
  - metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /version
  - /healthz
  - /healthz/*
  - /metrics
  - /metrics/cadvisor
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  - rollouts/scale
  - rollouts/status
  - experiments
  - analysistemplates
  - clusteranalysistemplates
  - analysisruns
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - sparkapplications/status
  - scheduledsparkapplications
  - scheduledsparkapplications/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - imagepolicywebhook
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keda.sh
  resources:
  - scaledjobs
  - scaledjobs/finalizers
  - scaledjobs/status
  - triggerauthentications
  - triggerauthentications/status
  - scaledobjects
  - scaledobjects/finalizers
  - scaledobjects/status
  - clustertriggerauthentications
  - clustertriggerauthentications/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - flinkoperator.k8s.io
  resources:
  - flinkclusters
  - flinkclusters/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - flink.apache.org
  resources:
  - flinkdeployments
  - flinkdeployments/status
  - flinksessionjobs
  - flinksessionjobs/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resourceNames:
  - granulate-maestro
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ''
  resourceNames:
  - granulate-service-account
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - granulate-cluster-role
  resources:
  - clusterroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - granulate-cluster-role-binding
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resourceNames:
  - grafana-config
  - argocd-cm
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ''
  resourceNames:
  - granulate-maestro-admission-controller-service
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - granulate-maestro-admission-controller.granulate.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - imagepolicywebhook
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - imagepolicywebhook
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: granulate-service-account
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: granulate-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: granulate-cluster-role
# These RBAC configurations are set for the "default" namespace, by default.
# If you are using a custom namespace for the granulate-agent, update the following namespace parameter before
# applying this configuration (the subject's namespace should match the granulate-agent namespace).
subjects:
  - kind: ServiceAccount
    name: granulate-service-account
    namespace: default
---
kind: PriorityClass
apiVersion: scheduling.k8s.io/v1
metadata:
  name: granulate-high-priority
value: 1000000
preemptionPolicy: Never
globalDefault: false
description: "This priority class should be used for Granulate daemonset only"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: granulate-maestro
  name: granulate-maestro
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: granulate-maestro
  template:
    metadata:
      labels:
        app: granulate-maestro
    spec:
      containers:
      - env:
        - name: STDOUT_LEVEL
          value: "10"
        - name: LOGS_ENABLE_STDOUT
          value: "1"
        - name: MAESTRO_CLIENT_ID
          value: CvzERSTEflNv4rXkFKsBNg==
        - name: MAESTRO_SERVICE_NAME
          value: k8s-cluster-test
        - name: MAESTRO_RUN_ON_K8S
          value: 'TRUE'
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MAESTRO_SERVER_HOST
          value: http://host.docker.internal:8080
        image: index.docker.io/granulate/maestro:1.27.12
        name: granulate-maestro
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: 2
            memory: 1.25Gi
          requests:
            cpu: 1
            memory: 800Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
      - name: granulate-secret
      priorityClassName: granulate-high-priority
      serviceAccountName: granulate-service-account
      terminationGracePeriodSeconds: 3

